port: 4002
permalinks: pretty
sass:
    style: expanded
collections:
  locations:
    output: true
    permalink: /:collection/:path/
  factions:
    output: true
    permalink: /:collection/:path/
  events:
    output: true
    permalink: /:collection/:path/
