port: 4002
permalinks: pretty
sass:
    style: expanded
collections:
  locations:
    output: true
    permalink: /:collection/:path/
  stores:
    output: true
    permalink: /:collection/:path/
  items:
    output: true
    permalink: /:collection/:path/
  factions:
    output: true
    permalink: /:collection/:path/
  families:
    output: true
    permalink: /:collection/:path/
  events:
    output: true
    permalink: /:collection/:path/
  npcs:
    output: true
    permalink: /:collection/:path/
  pcs:
    output: true
    permalink: /:collection/:path/
  quests:
    output: true
    permalink: /:collection/:path/
  maps:
    output: true
    permalink: /:collection/:path/
